### ISSUE TITLE
Use a hashing algorithm

### ISSUE THREAD

**Issue by vmkazakoff** [boringdesigners/boring-avatars#14]
Hi. Thanks for this app, first of all!

As I see, we have not so much of alternatives?

![image](https://user-images.githubusercontent.com/5445543/120168433-8103c680-c207-11eb-8a54-2721ad6e7202.png)

**Comment by kacgrzes** [comment]
The library could export some extra function like `createAvatar` factory that would create a component with some randomizer. For example:

```js

import Avatar, { createAvatar } from 'boring-avatars'

const MyAvatar = createAvatar({
  randomizer: Math.random, // but could also be randomizer-js or some other implementation for random function,
})

// and then, these two component would work the same, but the other would have a different randomizer implementation

<Avatar />
<MyAvatar />
```

**Comment by mattbasta** [comment]
I encountered this as well. It seems that the problem is that the algorithm to map a name to a number simply sums the ASCII values of each of the characters. In the example here (`23`, `32`, `41`, etc.) the ASCII codes always sum to the same value. Anagrams will always have identical numbers.

Moreover, _similar_ numbers will result in similar outputs. Since these numbers are base 10, names with only slightly different ASCII character totals will vary slightly in their number, meaning the higher digits will have less entropy than the lower digits. For instance, if two names sum to `1452` and `1434` respectively, the avatar features that pull the thousands and hundreds places will have identical features.

The fix here is to use a hashing algorithm with a lower probability of collisions (and near-collisions). One potential option is this:

https://werxltd.com/wp/2010/05/13/javascript-implementation-of-javas-string-hashcode-method/

It's short and simple, and would likely produce meaningfully better results without impacting bundle size or performance.

**Comment by mattbasta** [comment]
For reference, this is the function that would need updating: https://github.com/boringdesigners/boring-avatars/blob/master/src/lib/utilities.js#L1

**Comment by promet99** [comment]
Perhaps adding an option for different hashing algorithm can work

**Comment by josepmartins** [comment]
Hey @mattbasta 👋 , thanks for the proposal. We'll take a look on that soon 👍

**Comment by josepmartins** [comment]
@mattbasta @vmkazakoff Just changed the function to generate unique numbers from the name to avoid this cases and expand the number of variants in https://github.com/boringdesigners/boring-avatars/commit/b5b688eed58b824e7e87fb1c005f28892f57498d.

<img width="553" alt="Screenshot 2021-12-23 at 21 19 48" src="https://user-images.githubusercontent.com/912236/147288347-19f64baa-75ad-4afb-b67d-ddccb9198cdc.png">


I'll update the `npm` version later today. Thank you for your time and patience!
