### ISSUE TITLE
Vercel Payment Required

### ISSUE THREAD

**Issue by Jamalam360** [boringdesigners/boring-avatars#57]
**Describe the bug**
It seems that the project has exceeded Vercel usage limits, if you were not already aware.  A project like this might be able to generate enough sponsor revenue to sustain a higher Vercel plan, although I'm not a Vercel user so not sure. 

**To Reproduce**
1. Head to [the website](https://boringavatars.com/)

**Comment by Jamalam360** [comment]
![image](https://user-images.githubusercontent.com/56727311/208248158-97cf88ab-3835-42bd-826a-f05d6def5460.png)

**Comment by digi-com** [comment]
+1

This is causing an issue in one of our production apps, would be more than happy to contribute/sponsor the package in some regard, really appreciate the service as a whole — super useful.

**Comment by josiahbryan** [comment]
+1 Prod issue - happy to sponsor as well if option available

**Comment by fairbairn** [comment]
We would as well.  Happy to sponsor to get it back up, and keep it up.

**Comment by quiint** [comment]
+1

**Comment by alanhoskins** [comment]
Until they get it back up, I have forked it and hosted it at https://www.boringavatar.com/ and https://source.boringavatar.com/beam/120/Alan%20Hoskins?colors=264653,2a9d8f,e9c46a,f4a261,e76f51 for the hosted service.

**Comment by fairbairn** [comment]
> Until they get it back up, I have forked it and hosted it at https://www.boringavatar.com/ and https://source.boringavatar.com/beam/120/Alan%20Hoskins?colors=264653,2a9d8f,e9c46a,f4a261,e76f51 for the hosted service.

That was really nice of you alan.  We ended up using the service example and self-hosted it as well, so we won't be slamming you in the future.

**Comment by josiahbryan** [comment]
That was indeed very kind of you. Would you possibly be able to publish the code that handles the hosting, @alanhoskins ? or @fairbairn ...? I would like to do the same - mount it on some `express` route and let my own server serve up the data. Since I default (or did default) to using `boringavatars` via URL for profile photos until a user set their own, it would be wayyyyy to much work to go thru and replace each `<img` rendering with a conditional `url ? <img> : <Avatar>` etc...would much prefer to just host my own endpoint so I can swap URLs instead of swap components haha

**Comment by fairbairn** [comment]
> That was indeed very kind of you. Would you possibly be able to publish the code that handles the hosting, @alanhoskins ? or @fairbairn ...? I would like to do the same - mount it on some `express` route and let my own server serve up the data. Since I default (or did default) to using `boringavatars` via URL for profile photos until a user set their own, it would be wayyyyy to much work to go thru and replace each `<img` rendering with a conditional `url ? <img> : <Avatar>` etc...would much prefer to just host my own endpoint so I can swap URLs instead of swap components haha

I found this..

https://github.com/hihayk/boring-avatars-service.git

**Comment by ajhenry** [comment]
I'm also happy to sponsor ❤️

**Comment by josepmartins** [comment]
Hey there 👋 , the project and the service have been restored again. Seeing the interest and the high volume of usage, we are looking into a GitHub sponsor revenue to cover and upgrade to a pro plan in Vercel and dedicate time to upgrade and keeping the library updated.

Thanks for your patience 🙇

**Comment by josepmartins** [comment]
Hey all, we just opened a boring sponsors profile 🎉  ->  ✨  https://github.com/sponsors/boringdesigners  ✨  

The idea is to at least cover expenses as we moved our boring avatar service into a pro Vercel account. This way we could support close to 6GB of network bandwidth and 7M requests per day, work on opened issues/PRs and migrate to edge functions instead of serverless.

<img width="1325" alt="Screenshot 2023-02-07 at 18 35 22" src="https://user-images.githubusercontent.com/912236/217321279-4c181ada-f206-4a1e-bf2e-6c105cf9bdaa.png">


Thank you all for your patience and feedback.
