### ISSUE TITLE
Invalid type attribute warning in TypeScript

### ISSUE THREAD

**Issue by TheOrdinaryWow** [boringdesigners/boring-avatars#83]
**Describe the bug**
When using `<Avatar/>`, warning of inappropriate types for attributes `title` and `square` appears in console.

**To Reproduce**

boring-avatar.tsx
```tsx
import Avatar from "boring-avatars";
import { nanoid } from "nanoid";

export default function BoringAvatar({
  hash,
  size,
}: {
  hash: string | undefined;
  size: number;
}) {
  return (
    <Avatar
      variant="beam"
      size={size}
      name={hash || nanoid(8)}
      colors={["#3468C0", "#B2DEEC", "#FFDD95", "#FB6D48"]}
    />
  );
}
```

usage
```tsx
// `data.hash` could be any string
<BoringAvatar size={24} hash={data.hash} />
```

**Expected behavior**
Everything works fine.

**Screenshots**
![CleanShot 2024-09-03 at 13 32 41@2x](https://github.com/user-attachments/assets/219660c8-6ed8-4bb1-bd03-7f217d63bf2f)

**Desktop**
 - OS: macOS 18.0
 - Browser Safari
 - Version 18.0 (20619.1.26.31.6)
 - Package Version: v1.11.0
 - Node Version: v20.17.0
 - Package Manager: Bun 1.1.26
 - Frontend Tooling: Rsbuild v1.0.1-rc.0

**Additional context**
This issue is related to #25 .
Meanwhile, a TypeScript related issue https://github.com/boringdesigners/boring-avatars/issues/81#issuecomment-2322088216 needs to be followed up.

**Comment by josepmartins** [comment]
Hey @TheOrdinaryWow, thanks for pointing this out.

The warning you're encountering occurs because the `square` prop is being passed to the <svg> element, and it's not a recognized attribute for an SVG element. React is giving you warnings that it's trying to set a non-boolean attribute (square) to a boolean value (false), which isn't appropriate in this context. Same for the `title` attribute.

I just made some changes here: https://github.com/boringdesigners/boring-avatars/commit/a771b283fb7b12398aa03b628890d7e4af06dad6 and published a new version patch [v1.11.1 ](https://github.com/boringdesigners/boring-avatars/releases/tag/v1.11.1) fixing this and adjusting the typescript exports too.

Hope this helps 🙏
